# Generated by Django 3.0 on 2022-06-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0010_auto_20220517_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancie',
            name='vacancy_description',
            field=models.TextField(),
        ),
    ]
