# Generated by Django 3.0 on 2022-06-02 05:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_auto_20220602_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancie',
            name='vacancy_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
