# Generated by Django 3.0 on 2022-09-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_alter_category_id_alter_event_id_and_more'),
        ('indexapp', '0012_auto_20220602_1127'),
    ]

    operations = [
    ]
