# Generated by Django 3.0 on 2022-09-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0008_auto_20220914_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ministry_strength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=20)),
                ('executives', models.CharField(blank=True, max_length=20)),
                ('pro_and_mgmt', models.CharField(blank=True, max_length=20)),
                ('support', models.CharField(blank=True, max_length=20)),
                ('operational', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
