# Generated by Django 3.0 on 2022-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0009_ministry_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry_strength',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
