# Generated by Django 3.0 on 2022-09-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0009_auto_20220914_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office_of_minister',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
