# Generated by Django 3.0 on 2022-09-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0011_auto_20220914_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='finance_division',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='human_resource_division',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='ict_division',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='internal_audit',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='policy_planning_division',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='procurement_section',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
