# Generated by Django 4.0.4 on 2022-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220518_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
