# Generated by Django 3.0 on 2022-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_auto_20220914_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='ditt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorName', models.CharField(max_length=200, null=True)),
                ('directorPost', models.CharField(max_length=200, null=True)),
                ('directorMail', models.CharField(max_length=200, null=True)),
                ('directorPhoneNumber', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('total', models.CharField(blank=True, max_length=20)),
                ('executives', models.CharField(blank=True, max_length=20)),
                ('pro_and_mgmt', models.CharField(blank=True, max_length=20)),
                ('support', models.CharField(blank=True, max_length=20)),
                ('operational', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorName', models.CharField(max_length=200, null=True)),
                ('directorPost', models.CharField(max_length=200, null=True)),
                ('directorMail', models.CharField(max_length=200, null=True)),
                ('directorPhoneNumber', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('total', models.CharField(blank=True, max_length=20)),
                ('executives', models.CharField(blank=True, max_length=20)),
                ('pro_and_mgmt', models.CharField(blank=True, max_length=20)),
                ('support', models.CharField(blank=True, max_length=20)),
                ('operational', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='doim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorName', models.CharField(max_length=200, null=True)),
                ('directorPost', models.CharField(max_length=200, null=True)),
                ('directorMail', models.CharField(max_length=200, null=True)),
                ('directorPhoneNumber', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('total', models.CharField(blank=True, max_length=20)),
                ('executives', models.CharField(blank=True, max_length=20)),
                ('pro_and_mgmt', models.CharField(blank=True, max_length=20)),
                ('support', models.CharField(blank=True, max_length=20)),
                ('operational', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rsta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorName', models.CharField(max_length=200, null=True)),
                ('directorPost', models.CharField(max_length=200, null=True)),
                ('directorMail', models.CharField(max_length=200, null=True)),
                ('directorPhoneNumber', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('total', models.CharField(blank=True, max_length=20)),
                ('executives', models.CharField(blank=True, max_length=20)),
                ('pro_and_mgmt', models.CharField(blank=True, max_length=20)),
                ('support', models.CharField(blank=True, max_length=20)),
                ('operational', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='department_of_air_transport',
        ),
        migrations.DeleteModel(
            name='department_of_information_and_media',
        ),
        migrations.DeleteModel(
            name='department_of_it_telecom',
        ),
        migrations.DeleteModel(
            name='road_safety_and_transport_authority',
        ),
    ]
